### ISSUE TITLE
"Error: file_get_contents(C:\craft\vendor\bin/markdown)"

### ISSUE THREAD

**Issue by ragemous3** [pixelandtonic/craftnet#148]
Hello. 

Windows 10
Composer via ubuntu on windows sub system.
Chrome 
Localhost via MAMP :(

I'm trying to download plugins from the plugin-store first time but keeps getting this: 

_"Error: file_get_contents(C:\craft\vendor\bin/markdown): failed to open stream: No such file or directory"_

A file named markdown is in said folder in uri though the last backslash looks wrong but don't know how to fix it. I've set writing permissions and allows_url_fopen=On.

**Comment by angrybrad** [comment]
@ragemous3 can you share the full stack trace leading up to that error? If it's not on the screen, it'll be in the Craft `storage/logs` folder.

**Comment by ragemous3** [comment]
Sure. Ofcourse, should've done that in the first place. I backedup and changed binaryinstaller to use a backslash but still getting the same error but like this: "Error: file_put_contents(C:\MAMP\htdocs\training\vendor\bin\markdown)". Notice that the URI is correct now. I changed back to the original error. However, the markdown file is a 0 byte file with file-type: File(?). 

[yii\db\Command::execute] UPDATE `plugins` SET `licenseKeyStatus`='unknown', `licensedEdition`=NULL, `dateUpdated`='2019-03-21 06:25:20' WHERE `handle`='contact-form'
2019-03-20 23:26:02 [-][1][-][error][craft\controllers\BaseUpdaterController::actionComposerInstall] Error updating Composer requirements: file_put_contents(C:\MAMP\htdocs\training\vendor\bin/markdown): failed to open stream: No such file or directory
Output: <warning>Package "craftcms/vue-asset" listed for update is not installed. Ignoring.</warning>
Loading composer repositories with package information
Updating dependencies
Package operations: 10 installs, 0 updates, 0 removals
  - Installing psr/container (1.0.0): Downloading (connecting...)Downloading (0%)
Downloading (100%)
  - Installing pimple/pimple (v3.2.3): Downloading (connecting...)
Downloading (100%)
  - Installing container-interop/container-interop (1.2.0): Downloading (connecting...)
Downloading (100%)
  - Installing mrclay/props-dic (2.2.0): Downloading (connecting...)
Downloading (100%)
  - Installing mrclay/jsmin-php (2.4.0): Downloading (connecting...)
Downloading (100%)
  - Installing monolog/monolog (1.24.0): Downloading (connecting...)
Downloading (100%)
  - Installing intervention/httpauth (2.0.4): Downloading (connecting...)
Downloading (100%)
  - Installing tubalmartin/cssmin (v4.1.1): Downloading (connecting...)
Downloading (100%)
  - Installing mrclay/minify (3.0.3): Downloading (connecting...)
Downloading (100%)
  - Installing nystudio107/craft-minify (1.2.9): Downloading (connecting...)
Downloading (100%)
Writing lock file
Generating optimized autoload files

2019-03-20 23:26:02 [-][1][-][error][yii\base\ErrorException:2] yii\base\ErrorException: file_put_contents(C:\MAMP\htdocs\training\vendor\bin/markdown): failed to open stream: No such file or directory in C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer\BinaryInstaller.php:167
Stack trace:
#0 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\web\ErrorHandler.php(81): yii\base\ErrorHandler->handleError(2, 'file_put_conten...', 'C:\\MAMP\\htdocs\\...', 167)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'file_put_conten...', 'C:\\MAMP\\htdocs\\...', 167, Array)
#2 C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer\BinaryInstaller.php(167): file_put_contents('C:\\MAMP\\htdocs\\...', '#!/usr/bin/env ...')
#3 C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer\BinaryInstaller.php(146): Composer\Installer\BinaryInstaller->installUnixyProxyBinaries('C:\\MAMP\\htdocs\\...', 'C:\\MAMP\\htdocs\\...')
#4 C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer\BinaryInstaller.php(86): Composer\Installer\BinaryInstaller->installFullBinaries('C:\\MAMP\\htdocs\\...', 'C:\\MAMP\\htdocs\\...', 'bin/markdown', Object(Composer\Package\CompletePackage))
#5 C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer\LibraryInstaller.php(159): Composer\Installer\BinaryInstaller->installBinaries(Object(Composer\Package\CompletePackage), 'C:\\MAMP\\htdocs\\...', false)
#6 C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer\InstallationManager.php(147): Composer\Installer\LibraryInstaller->ensureBinariesPresence(Object(Composer\Package\CompletePackage))
#7 C:\MAMP\htdocs\training\vendor\composer\composer\src\Composer\Installer.php(308): Composer\Installer\InstallationManager->ensureBinariesPresence(Object(Composer\Package\CompletePackage))
#8 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\services\Composer.php(173): Composer\Installer->run()
#9 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\controllers\BaseUpdaterController.php(182): craft\services\Composer->install(Array, Object(Composer\IO\BufferIO))
#10 [internal function]: craft\controllers\BaseUpdaterController->actionComposerInstall()
#11 C:\MAMP\htdocs\training\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#12 C:\MAMP\htdocs\training\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\web\Controller.php(109): yii\base\Controller->runAction('composer-instal...', Array)
#14 C:\MAMP\htdocs\training\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('composer-instal...', Array)
#15 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\web\Application.php(297): yii\base\Module->runAction('pluginstore/ins...', Array)
#16 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\web\Application.php(561): craft\web\Application->runAction('pluginstore/ins...', Array)
#17 C:\MAMP\htdocs\training\vendor\craftcms\cms\src\web\Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 C:\MAMP\htdocs\training\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 C:\MAMP\htdocs\training\web\index.php(21): yii\base\Application->run()
#20 {main}
2019-03-20 23:25:15 [-][1][-][info][application] $_GET = [
    'p' => 'rackemuff/actions/pluginstore/install/composer-install'
]

$_POST = [
    'data' => '99a0d4128f7dda52191c2380c895eb8f07b259bc1f7b3e2139d875cb89a84075{\"packageName\":\"nystudio107/craft-minify\",\"handle\":\"minify\",\"edition\":\"standard\",\"version\":\"1.2.9\",\"requirements\":{\"nystudio107/craft-minify\":\"1.2.9\"},\"removed\":false,\"licenseKey\":null,\"returnUrl\":null,\"postPrecheckState\":{\"nextAction\":\"composer-install\",\"status\":\"Updating Composer dependencies (this may take a minute)…\"}

**Comment by ragemous3** [comment]
Any suggestions using another craft3-environment on windows is highly appreciated :).

**Comment by ragemous3** [comment]
Code causing the last slash to be put in the wrong direction in BinaryInstaller.php.
path: "vendor\composer\composer\src\Composer\Installer\BinaryInstaller.php"

```
  $this->initializeBinDir();
            $link = $this->binDir.'/'.basename($bin);
            if (file_exists($link)) {
                if (is_link($link)) {
                    // likely leftover from a previous install, make sure
                    // that the target is still executable in case this
                    // is a fresh install of the vendor.
                    Silencer::call('chmod', $link, 0777 & ~umask());
                }
                if ($warnOnOverwrite) {
                    $this->io->writeError('    Skipped installation of bin '.$bin.' for package '.$package->getName().': name conflicts with an existing file');
                }
                continue;
            }
```

**Comment by angrybrad** [comment]
Just so we're on the same page, this is purely in MAMP on Windows? Is any part of the Craft install using WSL?

**Comment by ragemous3** [comment]
The installation was done over WSL-Ubuntu Cli with composer. Installation on windows system drive (C://) and localhosted with MAMP which was a purely windows installation. 

Lack of time made me go for virtualbox with homestead so i'm afraid I cant recreate anything now. But if you have any more questions i'll happily answer them.
